///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package screen;
//
//import date.Data;
//import datechooser.model.exeptions.IncompatibleDataExeption;
//import datechooser.model.multiple.PeriodSet;
//import java.util.Calendar;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//
//
///**
// *
// * @author dm
// */
//public class Porcentagem extends javax.swing.JFrame {
//
//    /**
//     * Creates new form Porcentagem
//     */
//    public Porcentagem() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        lbDtReferencia = new javax.swing.JLabel();
//        dtReferencia = new datechooser.beans.DateChooserCombo();
//        btnGerar = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("SIMULADO Meta");
//        setLocation(new java.awt.Point(300, 300));
//        setName("frmEscolherData"); // NOI18N
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            public void windowOpened(java.awt.event.WindowEvent evt) {
//                formWindowOpened(evt);
//            }
//        });
//
//        lbDtReferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        lbDtReferencia.setText("Escolha a data referência:");
//        lbDtReferencia.setToolTipText("Defina a data referência do relatório, geralmente é o dia anterior");
//
//        dtReferencia.setCalendarPreferredSize(new java.awt.Dimension(400, 300));
//        dtReferencia.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 14));
//        dtReferencia.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 12));
//        dtReferencia.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
//
//        btnGerar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        btnGerar.setText("Gerar Relatório");
//        btnGerar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnGerarActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addContainerGap(179, Short.MAX_VALUE)
//                .addComponent(btnGerar)
//                .addContainerGap())
//            .addGroup(layout.createSequentialGroup()
//                .addGap(31, 31, 31)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(dtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(lbDtReferencia))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(29, 29, 29)
//                .addComponent(lbDtReferencia)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(dtReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
//                .addComponent(btnGerar)
//                .addGap(30, 30, 30))
//        );
//
//        dtReferencia.getAccessibleContext().setAccessibleName("Data referência");
//        dtReferencia.getAccessibleContext().setAccessibleDescription("Escolha a Data Referência");
//
//        getAccessibleContext().setAccessibleDescription("SIMULADO Meta");
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        PeriodSet dataPadrao = new PeriodSet();
//        Calendar cal = Calendar.getInstance();
//        cal.add(Calendar.DATE, -1); 
//        dataPadrao.add(cal);
//        try {
//            dtReferencia.setDefaultPeriods(dataPadrao);
//        } catch (IncompatibleDataExeption ex) {
//            Logger.getLogger(Porcentagem.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }//GEN-LAST:event_formWindowOpened
//
//    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_btnGerarActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Porcentagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Porcentagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Porcentagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Porcentagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Porcentagem().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton btnGerar;
//    private datechooser.beans.DateChooserCombo dtReferencia;
//    private javax.swing.JLabel lbDtReferencia;
//    // End of variables declaration//GEN-END:variables
//}
