/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import bd.sys.Custo;
import util.Utils;
import jtable.ResultSetTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rpmeta.RPMeta;
import date.Data;
import jtable.DespesasTableCellRenderer;



/**
 *
 * @author dm
 */
import java.io.IOException;
import java.util.Map;
import javax.swing.table.TableCellRenderer;
import org.apache.commons.mail.EmailException;
import rpmeta.iRPMeta;
public class DespesasCaixa extends javax.swing.JFrame {

    iRPMeta pdf;
    Map<String,String> todasB;
    
    /**
     * Creates new form DespesasCaixa
     */
    public DespesasCaixa() {
        initComponents();
        inicializar();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        grpPesquisa = new javax.swing.JPanel();
        labAno = new javax.swing.JLabel();
        cbAno = new javax.swing.JComboBox<>();
        labMes = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        cbSigla = new javax.swing.JComboBox<>();
        labB = new javax.swing.JLabel();
        cbNum = new javax.swing.JComboBox<>();
        btnPesquisar = new javax.swing.JButton();
        spDespesas = new javax.swing.JScrollPane();
        tbDespesas = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();
        btnTermos = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DESPESAS DO CAIXA");
        setLocation(new java.awt.Point(200, 200));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("frmDespesasCaixa"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 600));

        grpPesquisa.setToolTipText("Parâmetros de Pesquisa");

        labAno.setText("Ano:");
        labAno.setToolTipText("ANO");

        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        labMes.setText("Mês:");
        labMes.setToolTipText("MÊS");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbSigla.setToolTipText("");
        cbSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSiglaActionPerformed(evt);
            }
        });

        labB.setText("B:");
        labB.setToolTipText("B");

        cbNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grpPesquisaLayout = new javax.swing.GroupLayout(grpPesquisa);
        grpPesquisa.setLayout(grpPesquisaLayout);
        grpPesquisaLayout.setHorizontalGroup(
            grpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labB)
                .addGap(2, 2, 2)
                .addComponent(cbSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar))
        );
        grpPesquisaLayout.setVerticalGroup(
            grpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labAno)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labMes)
                    .addComponent(labB)
                    .addComponent(cbSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbMes.getAccessibleContext().setAccessibleName("Mês");
        cbMes.getAccessibleContext().setAccessibleDescription("Mês do Ano");

        spDespesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbDespesas.setAutoCreateRowSorter(true);
        tbDespesas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbDespesas.setToolTipText("");
        spDespesas.setViewportView(tbDespesas);

        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnTermos.setText("Termos");
        btnTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTermosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTermos)
                        .addGap(62, 62, 62)
                        .addComponent(btnFechar)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFechar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnTermos)))
                .addGap(18, 18, 18)
                .addComponent(spDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializar(){
        try {
            pdf = new iRPMeta("ontem");
        } catch (EmailException | IOException ex) {
            Logger.getLogger(DespesasCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        cbAno.setSelectedItem(pdf.data.dtReferenciayyyy());
        cbMes.setSelectedItem(pdf.data.dtReferenciaMM());
        
        todasB = pdf.fc.todasB();

        for (Map.Entry<String,String> entry : todasB.entrySet()) {
            cbNum.addItem(entry.getKey());
            cbSigla.addItem(entry.getValue());                        
        }

        cbNum.setSelectedIndex(0);
        cbSigla.setSelectedIndex(0);
    }
    
    
    private void pesquisar(){
        ResultSet rs;                

        String mes,ano,ini,fim;
        mes = cbMes.getSelectedItem().toString();
        ano = cbAno.getSelectedItem().toString();
        ini = Data.primeiroDiaMes(mes, ano).format(Data.formatarMMddyyyy());
        fim = Data.ultimoDiaMes(mes, ano).format(Data.formatarMMddyyyy());
        pdf.mw.setDespesas(ini,fim);
        rs = pdf.mw.despesas(cbNum.getSelectedItem().toString());
        
        String[] header = {"B","DATA","DESCRIÇÃO","VALOR"};

        try {
            tbDespesas.setModel(new ResultSetTableModel(rs, header));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(RPMeta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TableCellRenderer renderer = tbDespesas.getDefaultRenderer(Object.class);
	tbDespesas.setDefaultRenderer(Object.class, new DespesasTableCellRenderer(renderer));
        
       
    }
            
    
    private void cbSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSiglaActionPerformed
        // TODO add your handling code here:
        cbNum.setSelectedItem(Utils.getKeyByValue(todasB, cbSigla.getSelectedItem().toString()));
    }//GEN-LAST:event_cbSiglaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar();

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cbNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumActionPerformed
        // TODO add your handling code here:
            cbSigla.setSelectedItem(todasB.get(cbNum.getSelectedItem().toString()));
    }//GEN-LAST:event_cbNumActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTermosActionPerformed
        // TODO add your handling code here:

       try {
           ResultSet rs = pdf.cst.getTermos();
           while (rs.next()) {
               System.out.println(rs.getString(1) + ": " + rs.getString(2) + " - " + rs.getString(3) + " - " + rs.getString(4));
           }
       } catch (SQLException ex) {
           Logger.getLogger(Custo.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_btnTermosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespesasCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespesasCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespesasCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespesasCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        final DespesasCaixa dc = new DespesasCaixa();
        dc.setLocationRelativeTo(null);
        dc.setVisible(true);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            dc.pesquisar();
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnTermos;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbNum;
    private javax.swing.JComboBox<String> cbSigla;
    private javax.swing.JPanel grpPesquisa;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel labAno;
    private javax.swing.JLabel labB;
    private javax.swing.JLabel labMes;
    private javax.swing.JScrollPane spDespesas;
    private javax.swing.JTable tbDespesas;
    // End of variables declaration//GEN-END:variables
}
